pak_helpers/employer/urls.py
from django.urls import path, include

from . import views

app_name = 'employer'

urlpatterns = [
    path('create/', views.employerCreateView, name='create_employer'),
    path('update/', views.employerUpdateView, name='update_employer'),
    path('employer_dashboard/',
         views.employerDashboardView, name='dashboard_employer'),
    path('deactive/', views.employerDeactivateView, name='deactive'),


    # # ajaz requests urls
    # path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    # path('ajax/load-areas/', views.load_area, name='ajax_load_areas'),

]
 

pak_helpers/helper/urls.py
from django.urls import path
from . import views

app_name = 'helper'

urlpatterns = [
    path('create/', views.createHelplerView, name='create_helper'),
    path('update/', views.UpdateHelplerView, name='update_helper'),
    path('helper_dashboard/',
         views.helperDashboardView, name='helper_dashboard'),
    path('reviews/', views.helperReviewsView, name='helper_reviews'),
    path('deactive/', views.helperDeactivateView, name='deactive'),

 
]

pak_helpers/pak_helpers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404 

from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='home'),
    path('list/', views.listView, name='list_view'),
    path('helper_detail/<int:id>', views.detailView, name='detail_view'),

    path('helper/', include('helper.urls')),
    path('employer/', include('employer.urls')),

    path('contact/' , views.contactView , name= 'contact'),
    path('help/' , views.helpView , name= 'help'),

    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),


]

handler404 = 'helper.views.error_404_page'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pak_helpers/contact/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    message = models.TextField()

    def __str__(self):
        return self.message

class Question(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    question = models.CharField(max_length=1500)
    answer = models.CharField(max_length=1500)
    is_frequent = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.question

pak_helpers/contact/forms.py
from django import forms

from .models import Contact, Question


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'



class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

pak_helpers/contact/views.py
from django.shortcuts import render

# Create your views here.

pak_helpers/templates/404_page.html
{% extends 'base.html' %}

{% block container %}
<div class="container">

    <!-- 404 Error Text -->
    <div class="text-center">
      <div class="error mx-auto" data-text="404">404</div>
      <p class="lead text-gray-800 mb-5">Page Not Found</p>
      <a href="{% url 'homr' %}">&larr; Back to Home</a>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>


{% endblock %}

pak_helpers/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Carousel Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Hanalei&display=swap" rel="stylesheet">
    <!-- font-family: 'Hanalei', cursive;
font-family: 'Anton', sans-serif; -->
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Hanalei&display=swap" rel="stylesheet">
    <!-- font-family: 'Hanalei', cursive;
font-family: 'Do Hyeon', sans-serif; -->

    <style>
        #id_message {
            height: 130px;
        }
    </style>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <meta name="theme-color" content="#563d7c">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
</head>

<body>
    <header>
        {% include 'nav_bar.html' %}
    </header>

    <main role="main">

        {%  include 'carousel.html' %}

        {% block container %}


        {% endblock %}


        <!-- FOOTER -->
        {% include 'footer.html' %}

    </main>

    

</html>

pak_helpers/templates/carousel.html
{% load static %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img width="100%" height="100%" class="img-fluid" src="{% static 'img/one.jpg' %}" >
            <div class="container">
                <div class="carousel-caption rounded" style="background: rgba(97, 100, 98, 0.2);">
                    <h1 class="" style="font-weight: bolder;">We connect you to safe and trustworthy<br> help at your home</h1>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'help' %}" role="button">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img width="100%" height="100%" class="img-fluid" src="{% static 'img/two.jpg' %}" >
            <div class="container">
                <div class="carousel-caption rounded" style="background: rgba(97, 100, 98, 0.2);">
                    <h1 class="" style="font-weight: bolder;">We connect you to safe and trustworthy<br> help at your home</h1>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'help' %}" role="button">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img width="100%" height="100%" class="img-fluid" src="{% static 'img/three.jpg' %}" >
            <div class="container">
                <div class="carousel-caption rounded" style="background: rgba(97, 100, 98, 0.2);">
                    <h1 class="" style="font-weight: bolder;">We connect you to safe and trustworthy<br> help at your home</h1>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'help' %}" role="button">Learn more</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

pak_helpers/templates/contact_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block container %}
<link rel="stylesheet" href="{% static 'css/contact_us.css' %}" >
<div class="container contact-form">
    <div class="contact-image">
        <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
    </div>
    <form method="POST">
        {% csrf_token %}
        <h3>Drop Us a Message</h3>
       <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="text" name="name" class="form-control" placeholder="Your Name *" value="" />
                </div>
                <div class="form-group">
                    <input type="text" name="email" class="form-control" placeholder="Your Email *" value="" />
                </div>
                <div class="form-group btn btn-block">
                    <input type="submit"  class="btnContact" value="Send Message" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <textarea name="message" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

pak_helpers/templates/detail_view.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block container %}
<div class="container mb-5">
    
    <div class="row">

        <div class="col-md-4">
            <a href="{% url 'list_view' %}" class="btn rounded-0 btn-primary btn-block text-white mb-5"> back to helper list </a>
            <div class="d-flex justify-content-center">
                <img src="{{ helper.profile_picture.url }}" height="300px" width="300px" class="img img-fluid text-center  border border-secondary rounded-circle">
            </div>
            <br>
            <div class="">
                <p>
                    <strong>Username:</strong>{{helper.user.username}}
                </p>
            </div>
            
            <div class="">
                <p>
                    <strong>Contact Number:</strong>{{helper.contact_number}}
                </p>
            </div>
            <div class="">
                <p>
                    <strong>Daily Work Rate:</strong>{{helper.daily_work_rate}}
                </p>
            </div>
            

        </div>

        <div class="col-md-8">
            <div class="">
                <p>
                    <strong>Email:</strong>{{helper.user.email}}
                    <span class="float-right">
                        {{helper.user.date_joined|date}}
                    </span>
                </p>
            </div>
            <div class="">
                <p>
                    <strong>Rating:</strong>{{helper.rating}}
                </p>
            </div>
            <div class="">
                <p>
                    <strong>gender:</strong>{{helper.gender}}
                </p>
            </div>
            
            <div class="card col-12">
                <div class="card-header">
                    Description:
                </div>
                <div class="card-body">
                    {{helper.description}}                            
                </div>
            </div>

            <div>
                {% for i in category_list %}
                    <span class="btn btn-lg rounded-0 btn-info mt-5 lead">{{i.name}}</span>
                {% endfor %}
            </div>
            
        </div>

    </div>

</div>
{% endblock %}

pak_helpers/templates/footer.html
<footer class="container ">

    <footer class="footer fixed-bottom position-relative bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; PakHelpers {% now 'Y' %} </span>
            </div>
        </div>
    </footer>
</footer>

pak_helpers/templates/help.html
{% extends 'base.html' %}
{% block container %}

<div class="container">
    <div class="row">
        <h1 class="h3 mb-2 text-gray-800">Frequently asked questions:</h1>
        {% for i in questions %}
        {% if i.is_frequent %}

        <div class="mb-4 border-left-info">
            <div class="card bg-primary text-white shadow">
              <div class="card-body">
                <strong class="text-info">Name:</strong>{{i.name}}
                <div class="text-white-50 small"><strong class="text-info">Question:</strong>{{i.question}}</div>
                <div class="text-white-50 small"><strong class="text-info">Answer:</strong>{{i.answer}}</div>
              </div>
            </div>
        </div>

        {% endif %}
        {% endfor %}

    </div>
</div>

{% endblock %}

pak_helpers/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block container %}
<div class="container marketing">
    <!-- Three columns of text below the carousel -->
    <h1 class="h3 mb-2 text-gray-800">Our top Helpers:</h1>
    <div class="row">
        {% for i in helpers %}
        <div class="col-lg-4">
            <img width="100%" height="100%" class="img-fluid rounded-circle" style="max-height: 170px; max-width: 170px;"
                src="{{ i.profile_picture.url }}">
            <h2>{{ i.user.username }}</h2>
            <p>
                {{ i.description }}
            </p>
            <p><a class="btn btn-secondary" href="{% url 'detail_view' i.user.pk %}" role="button">View details &raquo;</a></p>
        </div>

        {% endfor %}
    </div><!-- /.row -->
    <a href="{% url 'list_view' %}" class="btn btn-primary btn-lg btn-facebook btn-block"><i class="fab fa-facebook-f fa-fw"></i> View All Helpers</a>


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">


    <div class="row mb-4">
        <div class="col-md-6  border-right">
            <div class="text-center d-flex justify-content-center my-1">
                <img class="  img-fluid" src="{% static 'img/helper.png' %}" style="max-height: 300px;">
            </div>
            <a href="{% url 'helper:create_helper' %}" class="btn btn-lg btn-outline-warning rounded-0 text-center btn-block"> Become Helper </a>
            
        </div>

        <div class="col-md-6" >
            <div class="text-center d-flex justify-content-center my-1">
                <img class="  img-fluid" src="{% static 'img/employer.svg' %}" style="min-height: 300px;">
            </div>           
            <a href="{% url 'employer:create_employer' %}" class="btn btn-lg btn-outline-warning rounded-0 text-center btn-block"> Become Employer </a>

        </div>
    </div>


    <hr class="featurette-divider">




    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">We are here to <span class="text-muted">provide relibale help.</span>
            </h2>
            <ul style="font-weight: bolder;">
                <li class="lead">This is marketplace to map the work force with local work demand</li>
                <li>select worker skills​ , ​rate and ​ customer reviews</li>
            </ul>
        </div>
        <div class="col-md-5">
            <img width="100%" height="100%" src="{% static 'img/back1.jpg' %}" class="img-fluid">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">We are here to <span class="text-muted">provide relibale help.</span>
            </h2>
            <ul style="font-weight: bolder;">
                <li class="lead">This is marketplace to map the work force with local work demand</li>
                <li>select worker skills​ , ​rate and ​ customer reviews</li>
                <li>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis, repellendus!</li>
            </ul>
        </div>
        <div class="col-md-5 order-md-1">
            <img width="100%" height="100%" src="{% static 'img/back2.jpg' %}" class="img-fluid">
        </div>
    </div>

    <hr class="featurette-divider">
</div><!-- /.container -->

{% endblock %}

pak_helpers/templates/list_view.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block container %}
<div class="container mb-5">
    <div class="row">
        <!-- search  -->
        <div class="col-md-3 ">

            <form>
                {{myFilter.form|crispy}}
                <input type="submit" class="btn btn-block btn-primary" value="Search">
            </form>

        </div>
        <!-- cards  -->
        <!-- List of all helpers -->
        <div class="col-md-9 ">
            <div class="row">
                {% for i in helpers %}
                <div class="col-md-4">
                    <a href="{% url 'detail_view' i.user.id %}" style="text-decoration: none;">
                        <div class="card mb-4 box-shadow text-dark ">
                            <div class="text-light bg-dark px-2">
                                <span> {{i.user.username}} </span>
                                <small class=" float-right">{{i.user.date_joined|date}}</small>
                            </div>
                            <img class="card-img-right flex-auto d-none d-block" src="{{ i.profile_picture.url }}"
                                alt="image of emp" height="200px;">
                            <div class="card-body bg-dark text-light">
                                <p class="card-text lead"><strong class="text-success">Work
                                        rate:</strong>{{i.daily_work_rate}}</p>
                                <p class="card-text lead"><strong class="text-success">Rating:</strong>{{i.rating}}</p>
                                <p class="card-text"><strong class="text-success">Genger:</strong>{{i.gender}}</p>
                                <p class="card-text"><strong
                                        class="text-success">Location:</strong><small>{{i.area}},{{i.city}}</small></p>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>

            {% if helpers.has_other_pages %}
            <ul class="pagination justify-content-center">
                {% if helpers.has_previous %}
                <li><a class="page-link" href="?page={{ helpers.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="page-link disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in helpers.paginator.page_range %}
                {% if helpers.number == i %}
                <li class="page-link bg-primary text-light"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                <li><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if helpers.has_next %}
                <li><a class="page-link" href="?page={{ helpers.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="page-link" class="page-item disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}

        </div>
    </div>

</div>
{% endblock %}

pak_helpers/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Floating labels example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/floating-labels/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <link href="{% static 'css/login_style.css' %}" rel="stylesheet">
</head>

<body>



    <form class="form-signin" method="POST">
        <div class="text-center mb-4">
            <img class="mb-4 rounded-circle border border-success" src="{% static 'img/log_pic.jpg' %}" alt="" width="72" height="72">
            <a href="{% url 'home' %}" style="text-decoration: none;">
                <h1 class="h3 mb-3 font-weight-normal">
                    <span style="color: darkgreen;">Pak</span>
                    <span style="color: greenyellow;">Helpers</span>
                </h1>
            </a>
            <p>
                Please enter your username and password for login.
            </p>
        </div>

        <div class="form-label-group">
            <input type="text" class="form-control" placeholder="username" name='username' required autofocus>
            <label>Enter Username</label>
        </div>

        <div class="form-label-group">
            <input type="password" class="form-control" placeholder="Password" name='password' required>
            <label for="inputPassword">Password</label>
        </div>
        {% csrf_token %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>

        {% if messages %}
            <ul class="messages test-success">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                Want to become Helper? <a href="{% url 'helper:create_helper' %}" class="ml-2">Sign Up</a>
            </div>
            <div class="d-flex justify-content-center links">
                Want to become Employer? <a href="{% url 'employer:create_employer' %}" class="ml-2">Sign Up</a>
            </div>
        </div>

        <p class="mt-5 mb-3 text-muted text-center">Copyright &copy; PakHelpers {% now 'Y' %} </p>

    </form>
</body>

</html>

pak_helpers/templates/nav_bar.html
{% load auth_extras %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top " style="background-color: mediumseagreen;">
    <a class="navbar-brand" href="{% url 'home' %}">
        <span class="" style="color: green; font-family: 'Anton', cursive;">Pak</span>
        <span class="" style="color: greenyellow; font-family: 'Do Hyeon', sans-serif; ">Helpers</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'help' %}">Help<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'contact' %}">Contact us<span class="sr-only">(current)</span></a>
            </li>
        </ul>


        <ul class="navbar-nav ml-auto">

            {% if request.user|has_group:"helper" %}
            <li class="nav-item active">
                <a class="mr-3  nav-link" href="{% url 'helper:helper_dashboard' %}">View Details <span class="sr-only">(current)</span></a>
            </li> 
            {% elif request.user|has_group:"employer" %}
            <li class="nav-item active">
                <a class="mr-3  nav-link" href="{% url 'employer:dashboard_employer' %}">View Details <span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="mr-3   nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
            </li>
            {% endif %}

        </ul>

        
    </div>
</nav>