pak_helpers/helper/urls.py
from django.urls import path
from . import views

app_name = 'helper'

urlpatterns = [
    path('create/', views.createHelplerView, name='create_helper'),
    path('update/', views.UpdateHelplerView, name='update_helper'),
    path('helper_dashboard/',
         views.helperDashboardView, name='helper_dashboard'),
    path('reviews/', views.helperReviewsView, name='helper_reviews'),
    path('deactive/', views.helperDeactivateView, name='deactive'),

 
]

pak_helpers/pak_helpers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404 

from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='home'),
    path('list/', views.listView, name='list_view'),
    path('helper_detail/<int:id>', views.detailView, name='detail_view'),

    path('helper/', include('helper.urls')),
    path('employer/', include('employer.urls')),

    path('contact/' , views.contactView , name= 'contact'),
    path('help/' , views.helpView , name= 'help'),

    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),


]

handler404 = 'helper.views.error_404_page'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pak_helpers/helper/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django import template
from django.contrib.auth.models import Group


class Helper(models.Model):
    option = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profile_picture = models.ImageField(
        upload_to='helper_img', null=True, blank=True, default='helper_img/def_img.png')
    contact_number = models.CharField(max_length=13)
    cnic = models.CharField(max_length=15)
    gender = models.CharField(max_length=10, choices=option, default='Male')
    description = models.TextField(max_length=5000)
    daily_work_rate = models.IntegerField()
    profile_visible = models.BooleanField(null=True)
    age = models.SmallIntegerField(null=True)
    category = models.ManyToManyField('Category',null=True, blank=True)
    province = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    area = models.CharField(max_length=50, null=True, blank=True)
    rating = models.IntegerField(null=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.profile_picture.path)
        output_size = (500, 500)
        img.thumbnail(output_size)
        img.save(self.profile_picture.path)


class Rewiew(models.Model):
    user = models.ForeignKey(Helper, on_delete=models.SET_NULL, null=True)
    star = models.IntegerField()
    comment = models.TextField(max_length=1500, default='.')

    def __str__(self):
        return self.user.user.username


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Sub_Category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

pak_helpers/templates/dash/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{request.user}} Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'css/all.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb_admin.css' %}" rel="stylesheet">


</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- This is Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'helper:helper_dashboard' %}">
                <div class="sidebar-brand-text mx-3">{{ request.user }}<br> Dahboard </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item lead">
                <a class="nav-link" href="{% url 'home' %}">
                    <span>PakHelpers</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="nav-item" >
                
                <a class="nav-link"  href=" {% url 'helper:helper_dashboard'  %}" >
                    <span>User Menu</span>
                </a>
            </div>

            <div class="nav-item" >
                
                <a class="nav-link"  href=" {% url 'detail_view' id=request.user.helper.id   %}" >
                    <span>View Public Profile</span>
                </a>
            </div>

            <li class="nav-item ">
                <a class="nav-link active" href="{% url 'helper:update_helper'  %}">
                    <span>Update Profile</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'helper:helper_reviews' %}">
                    <span>your Review</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'helper:deactive' %}">
                    <span>Deactivate Account</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <svg id="sidebarToggle" class="bi bi-grid" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M1 2.5A1.5 1.5 0 012.5 1h3A1.5 1.5 0 017 2.5v3A1.5 1.5 0 015.5 7h-3A1.5 1.5 0 011 5.5v-3zM2.5 2a.5.5 0 00-.5.5v3a.5.5 0 00.5.5h3a.5.5 0 00.5-.5v-3a.5.5 0 00-.5-.5h-3zm6.5.5A1.5 1.5 0 0110.5 1h3A1.5 1.5 0 0115 2.5v3A1.5 1.5 0 0113.5 7h-3A1.5 1.5 0 019 5.5v-3zm1.5-.5a.5.5 0 00-.5.5v3a.5.5 0 00.5.5h3a.5.5 0 00.5-.5v-3a.5.5 0 00-.5-.5h-3zM1 10.5A1.5 1.5 0 012.5 9h3A1.5 1.5 0 017 10.5v3A1.5 1.5 0 015.5 15h-3A1.5 1.5 0 011 13.5v-3zm1.5-.5a.5.5 0 00-.5.5v3a.5.5 0 00.5.5h3a.5.5 0 00.5-.5v-3a.5.5 0 00-.5-.5h-3zm6.5.5A1.5 1.5 0 0110.5 9h3a1.5 1.5 0 011.5 1.5v3a1.5 1.5 0 01-1.5 1.5h-3A1.5 1.5 0 019 13.5v-3zm1.5-.5a.5.5 0 00-.5.5v3a.5.5 0 00.5.5h3a.5.5 0 00.5-.5v-3a.5.5 0 00-.5-.5h-3z" clip-rule="evenodd"/>
                  </svg>
            </div>

        </ul>
        <!-- End of Sidebar -->


        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content  -->
            <div id="content">

                <!-- This is top navbar -->
                <nav class=" navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class=" d-none disabled d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class=" form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>

                        </div>
                    </form>


                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fa fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>



                        <!-- Nav Item - Messages -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-envelope fa-fw"></i>
                                <!-- Counter - Messages -->
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="messagesDropdown">
                                <h6 class="dropdown-header">
                                    Rewiew Center
                                </h6>
                                {% for i in request.user.helper.rewiew_set.all|slice:":1" %}
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60"
                                            alt="">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div class="font-weight-bold">
                                        <div class="text-truncate">{{ i.comment }}</div>
                                        <div class="small text-gray-500">{{i.star}}</div>
                                    </div>
                                </a>
                                {% endfor %}
                                
                                <a class="dropdown-item text-center small text-gray-500" href="{% url 'helper:helper_reviews' %}">view all reviews</a>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information / logout -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span
                                    class="mr-2 d-none d-lg-inline text-gray-600 small font-weight-bolder">{{ request.user }}</span>
                                <img class="img-profile rounded-circle" src="{{ request.user.helper.profile_picture.url }}">
                            </a>
                            <!-- Dropdown - User Information -->

                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'helper:update_helper' %}">
                                    <i class="fa fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Update info
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    <i class="fa fa-sign-out mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- This is main body of page -->

                    {% block content %}



                    {% endblock %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            {% include 'footer.html' %}
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'js/easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/admin.min.js' %}"></script>

</body>

</html>

pak_helpers/templates/dash/deactivate_account.html
{% extends 'dash/base.html' %}

{% block content %}

<h1 class="h3 mb-1 text-gray-800">Are you sure you want to deactivate your account:</h1>

<h4>Account name :
    <strong>
        {{request.user.username}}
    </strong>
</h4>

<form method="POST">
    {% csrf_token %}
    <a href="{% url 'helper:helper_dashboard' %}" class="btn btn-primary rounded-0 text-white">Cancel</a>
    <input type="submit" value="Confirm Delete" class="btn btn-danger rounded-0">
</form>



{% endblock %}

pak_helpers/templates/dash/helper_dashboard.html
{% extends 'dash/base.html' %}


{% block content %}


<div class="row">
    <div class="card border-left-primary shadow h-100 py-2 col-md-3 mx-1">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Rating</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{request.user.helper.rating}}</div>
                </div>
                <div class="col-auto">
                    <i class="fa fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div> 
        </div>
    </div>
    <div class="card border-left-warning shadow h-100 py-2 col-md-3 mx-1">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Loyalty Points</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">100</div>
                </div>
                <div class="col-auto">
                    <i class="fa fa-chart-pie fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="card border-left-info shadow h-100 py-2 col-md-3 mx-1">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Profile Views</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                </div>
                <div class="col-auto">
                    <i class="fa fa-chart-line fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Comments of user only 2 -->
<div class="row my-5">
    <div class="col-md-6">
        <h3>Review:</h3>
        {% if request.user.helper.rewiew_set.all %}
        {% for i in request.user.helper.rewiew_set.all|slice:":2" %}
        <div class="card mb-3">
            <div class="card-header">
                Stars: {{i.star}}
            </div>
            <div class="card-body">
                {{i.comment}}
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="card mb-3">
            <div class="card-header">
                No Review about you have written yet
            </div>
            <div class="card-body">
                ...
            </div>
        </div>
        {% endif %}
    </div>
    <div class="col-md-6">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Actions</h6>
            </div>
            <div class="card-body">
                <a href="{% url 'helper:update_helper' %}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fa fa-flag"></i>
                    </span>
                    <span class="text">Update Profile</span>
                </a>
                <div class="my-2"></div>
                <a href="{% url 'helper:helper_reviews' %}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fa fa-check"></i>
                    </span>
                    <span class="text">View Reviews </span>
                </a>
                <div class="my-2"></div>
                <a href="{% url 'helper:deactive' %}" class="btn btn-danger btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fa fa-info-circle"></i>
                    </span>
                    <span class="text">Deactivate Account</span>
                </a>
            </div>
        </div>

    </div>

</div>


{% endblock %}

pak_helpers/templates/dash/reviews.html
{% extends 'dash/base.html' %}

{% block content %}

<h1 class="h3 mb-1 text-gray-800">Reviews:</h1>

{% if request.user.helper.rewiew_set.all %}
{% for i in request.user.helper.rewiew_set.all %}
<div class="card mb-3">
    <div class="card-header">
        Stars: {{i.star}}
    </div>
    <div class="card-body">
        {{i.comment}}
    </div>
</div>
{% endfor %}
{% else %}
<div class="card mb-3">
    <div class="card-header">
        No Review about you have written yet
    </div>
</div>
{% endif %}



{% endblock %}

pak_helpers/templates/dash/update_helper.html
{% extends 'dash/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">

    <form method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-3">
                <img src="{{ request.user.helper.profile_picture.url }}" height="400px" width="400px"
                    class="img img-fluid rounded-circle">
                {{ form2.profile_picture.name  }}
                <input type="file" name="profile_picture" accept="image/*" id="id_profile_picture">
                <hr>
                <div class="form-group ">
                    {{ form2.contact_number|as_crispy_field  }}
                </div>
                <div class="form-group mt-3">
                    {{ form2.daily_work_rate|as_crispy_field  }}
                </div>
                <div class="form-group">
                    {{ form2.age|as_crispy_field  }}
                </div>
            </div>

            <div class="col-md-9">
                <div class="form-group ">
                    {{ form2.description|as_crispy_field  }}
                </div>
                <div class="form-group ">
                    {{ form2.category|as_crispy_field  }}
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        {{ form2.province|as_crispy_field  }}
                    </div>
                    <div class="form-group col-md-4">
                        {{ form2.city|as_crispy_field  }}
                    </div>
                    <div class="form-group col-md-4">
                        {{ form2.area|as_crispy_field  }}
    
                    </div>
                </div>
        </div>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mb-5">Update Infomation</button>
    </form>
    <div class="text-danger">
        {{form2.errors}}
    </div>
</div>




<!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_province").change(function () {
        var url = $("#personForm").attr("data-cities-url"); // get the url of the `load_cities` view
        var provinceId = $(this).val(); // get the selected country ID from the HTML input

        $.ajax({ // initialize an AJAX request
            url: url, // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'province': provinceId // add the country id to the GET parameters
            },
            success: function (data) { // `data` is the return of the `load_cities` view function
                $("#id_city").html(
                    data
                    ); // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script> -->


<!-- <script>
    $("#id_city").change(function () {
        var url = $("#personForm").attr("data-area-url");
        var cityId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'city': cityId
            },
            success: function (data) {
                $("#id_area").html(data);
            }
        });

    });
</script> -->

{% endblock %}